package:
  name: mameshiba
  version: "0.1.0"

build:
  number: 0
  noarch: generic
  script: echo "Dependency-only package for MameShiba."

requirements:
  host:
    - python =3.11.0
  run:
    - python =3.11.0
    - pandas ==1.5.3
    - statsmodels ==0.13.5
    - numexpr ==2.8.4
    - pysam ==0.23.0
    - scanpy ==1.9.5
    - numpy ==1.26.4
    - pyyaml ==6.0.2
    - regtools ==1.0.0
    - subread ==2.0.8
    - stringtie ==3.0.0

test:
  commands:
    - python -c "import pandas, statsmodels.api, numexpr, pysam, scanpy, numpy, yaml"

about:
  home: https://github.com/Sika-Zheng-Lab/Shiba
  license: MIT
  summary: "mameshiba installs only the dependencies needed to run MameShiba."
  description: |
    mameshiba is a minimal conda meta-package that installs all dependencies required
    for running MameShiba (https://github.com/Sika-Zheng-Lab/Shiba). After installing, clone
    the Shiba GitHub repository and run 'python shiba.py'.
  dev_url: https://github.com/Sika-Zheng-Lab/Shiba

extra:
  recipe-maintainers:
    - naotokubota
